openapi: 3.0.3
info:
  title: API Specification for create an estimate documents
  version: 1.0-SNAPSHOT
servers:
  - url: http
paths:
  /estimate:
    post:
      tags:
        - Estimate
      summary: create estimate
      description: create estimate
      operationId: createEstimate
      requestBody:
        description: object that content the document data to created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EstimateDTO'
        required: true
      responses:
        201:
          description: estimate create successfully
components:
  schemas:
    EstimateDTO:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
          description: Creation date and time
          example: "2021-01-30T08:30:00Z"